server:
    port: 4042

spring:
    datasource:
        # url: jdbc:h2:file:./ignore/db/tbotdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:/db/init-db.sql'
        # url: jdbc:h2:mem:tbotdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:/db/init-db.sql'
        url: jdbc:mariadb://localhost:4340/ruler
        driverClassName: org.mariadb.jdbc.Driver
        username: ${DB_APP_USERNAME}
        password: ${DB_APP_PASSWORD}
        hikari:
            schema: ruler
    liquibase:
        url: jdbc:mariadb://localhost:4340/ruler
        liquibase-schema: ruler
        user: ${DB_ADMIN_USERNAME}
        password: ${DB_ADMIN_PASSWORD}

ruler:
    fileRepository:
        load:
            loadOnStartup: false
            path: ignore/config-dev
        dump:
            jsonFiles:
                ignore/dump/json
            sqlFiles:
                ignore/dump/sql
