server:
    port: 4040

spring:
    datasource:
        url: _secret_
        driverClassName: org.mariadb.jdbc.Driver
        username: _secret_
        password: _secret_
        hikari:
            schema: ruler
    liquibase:
        url: _secret_
        liquibase-schema: ruler
        user: _secret_
        password: _secret_

ruler:
    fileRepository:
        load:
            path: /data/load
            loadOnStartup: false
        dump:
            jsonFiles:
                data/dump/json
            sqlFiles:
                data/dump/sql
