server:
    port: 4040

spring:
    datasource:
        url: jdbc:h2:file:/data/h2/tbotdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:/db/init-db.sql'
        driverClassName: org.h2.Driver
        username: tbot
        password: password
        hikari:
            schema: ruler

ruler:
    fileRepository:
        load:
            path: /config
            loadOnStartup: false
        dump:
            jsonFiles:
                data/dump/json
            sqlFiles:
                data/dump/sql
