spring:
    application:
        name: ThingBot Ruler Service
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jmx:
        enabled: false
    datasource:
        url: jdbc:h2:mem:tbotdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:/db/init-db.sql'
    liquibase:
        change-log: classpath:/db/changelog/db-changelog-master.yaml
    thymeleaf:
        enabled: true
        cache: false
        prefix: classpath:/console/
        suffix: .html
        mode: HTML
        servlet:
            content-type: text/html
        encoding: UTF-8
        enable-spring-el-compiler: true

security:
    basic:
        enabled: false

management:
    security:
        enabled: false

eureka:
    client:
        enabled: false

ruler:
    broker:
        emissionQueueLength: 200
        collectionQueueLength: 200
    restService:
        connectionTimeout: 1000
        readTimeout: 2000
        retryCount: 5