### Gets stencil by owner and type
# @name = StencilGetByOwnerAndType

< {%
    request.variables.set("owner", "tbot-panel");
    request.variables.set("type", "layout");
%}
GET http://{{host-tbot-ruler}}/admin/stencils/owners/{{owner}}/types/{{type}}
Content-Type: application/json
