FLUSH PRIVILEGES;
CREATE OR REPLACE USER 'rulerAdmin'@'%' IDENTIFIED BY 'tYDyhhPdDgzA!F9';
GRANT ALL PRIVILEGES ON ruler.* TO 'rulerAdmin'@'%';

CREATE OR REPLACE USER 'rulerApp'@'%' IDENTIFIED BY '#23LZ#K995ZdqRb';
GRANT SELECT, INSERT, UPDATE, DELETE ON ruler.* TO 'rulerApp'@'%';

FLUSH PRIVILEGES;