server:
    port: 4042

spring:
    datasource:
        url: jdbc:h2:file:./ignore/db/tbotdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:/db/init-db.sql'
#        url: jdbc:h2:mem:tbotdb;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:/db/init-db.sql'

ruler:
    thingsConfig:
        path: ignore/config-dev
    dump:
        jsonFiles:
            ignore/dump/json
        sqlFiles:
            ignore/dump/sql
