### Update actuator state
# @name = ActuatorStateUpdate

< {%
    request.variables.set("actuatorUuid", "actr-d6043d86-cfcd-4067-af26-830f2ab52066");
    request.variables.set("widgetUuid", "wdgtc-ec01c493-1fa5-406a-a674-9c0e54e29857");
    request.variables.set("payloadType", "Trigger");
%}
PUT http://{{host-tbot-ruler}}/actuators/{{actuatorUuid}}/state
Content-Type: application/json

{
    "widgetUuid": "{{widgetUuid}}",
    "payloadType": "{{payloadType}}"
}