spring:
  application:
    name: ThingBot Ruler Console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jmx:
    enabled: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  client:
    enabled: false
