### Update actuator state
# @name = ActuatorStateUpdate

< {%
    request.variables.set("actuatorUuid", "actr-82716ace-1ac8-4533-bdbd-c249fa6099fd");
    request.variables.set("widgetUuid", "wbhk-ee78fbd9-2582-4fe0-bfc3-bc7d37f3a4bd");
    request.variables.set("payloadType", "Trigger");
%}
PUT http://{{host-tbot-ruler}}/actuators/{{actuatorUuid}}/state
Content-Type: application/json

{
    "widgetUuid": "{{widgetUuid}}",
    "payloadType": "{{payloadType}}"
}
