### Update actuator state
# @name = ActuatorStateUpdate

PUT http://{{host-tbot-ruler}}/actuators/actr-799c2261-1e01-4ae0-b92e-321afd705140/state
Content-Type: application/json

{
    "widgetUuid": "wdgt-test",
    "payloadType": "OnOff",
    "payload": {
        "on": "true"
    }
}