plugins {
    id 'com.palantir.docker' version '0.36.0'
    id 'com.palantir.docker-run' version '0.36.0'
}

def imageName = 'tbot-ruler-dev-db'

repositories {
    mavenLocal()
    mavenCentral()
}

dockerPrepare.doLast {
    println("Found and used docker file: " + docker.resolvedDockerfile)
}

docker {
    name "${imageName}"

    buildx true
    noCache true

    copySpec.with {
        from("sql-files")
        into("sql-files")
    }
}

dockerRun {
    name "${imageName}"
    image "${imageName}"
    ports '4340:3306'
    volumes "${parent.projectDir}/ignore/db": '/var/lib/mysql'
    clean
}

tasks.dockerRun.dependsOn = [
        dockerRemoveContainer
]

task dockerStopRemoveRun {
    dependsOn 'dockerStop'
    dependsOn 'dockerRemoveContainer'
    dependsOn 'dockerRun'
    tasks.findByName('dockerRun').mustRunAfter 'dockerRemoveContainer'
    tasks.findByName('dockerRemoveContainer').mustRunAfter 'dockerStop'
}
